name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Starting Apply Workflow
        run: echo "Starting the apply jobs..."

  backend-apply:
    name: Apply - backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/backend
    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Export ARM credentials for Terraform backend
        run: |
          echo "ARM_CLIENT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - run: terraform init
      - run: terraform apply -auto-approve

  network-apply:
    name: Apply - network
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/network
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - run: terraform init
      - run: terraform apply -auto-approve

  aks-apply:
    name: Apply - aks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/aks
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - run: terraform init
      - run: terraform apply -auto-approve

  weather-app-apply:
    name: Apply - weather-app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/weather-app
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - run: terraform init
      - run: terraform apply -auto-approve
